spring:
  profiles:
    # 激活环境：dev 开发版 | prod 发布版
    active: dev
  datasource:
    url: jdbc:mysql://101.42.47.30:3306/xxl-job?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: xxl-job
    password: XXL-JOB
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis 配置（符合 Spring Boot 3.2.5 推荐写法）
  data:
    redis:
      host: 101.42.47.30
      port: 6379
      password: WebCrawlerRedis
      database: 0
      timeout: 5s
      lettuce:
        pool:
          max-active: 8
          max-idle: 4
          min-idle: 0
          max-wait: 1ms

# JWT配置
jwt:
  secret: WebCrawlerSecretMadeByChenQiPengAnMinHuJiaRong
  token-expiration: 86400
  capcha-expiration: 60

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 短信服务配置
sms:
  aliyun:
    host: https://gyytz.market.alicloudapi.com
    path: /sms/smsSend
    method: POST
    appcode: f73828f54e754318ab549e18357e713c
    smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
    templateId: 908e94ccf08b4476ba6c876d13f084ad
    expireTime: 5

crawler:
  pageList:
    searchMethod: 0 # 0代表模糊查询 ， 1代表精确查询(爬虫名称）

