server:
  port: 8080

xxl:
  job:
    admin:
      addresses: http://101.42.47.30:8081/xxl-job-admin
      accessToken: default_token
      username: admin
      password: 123456
    executor:
      appname: web-crawler-xxl-job-andre
      address:
      ip:
      port: 0
      logpath: /app/logs
      logretentiondays: 30